[package]
name = "wg_mng_cbind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
basis = { path = "../basis" }
libc = "0.2.137"

[build-dependencies]
bindgen = "0.66.0"
cc = "1.0.78"
