name: tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: fmt check
        run: cargo fmt --all -- --check

      - name: install iproute and wireguard
        run: |
          sudo apt-get update
          sudo apt-get install -y iproute2 wireguard-tools

      - name: run wghttp route tests
        run: cargo test -p wghttp

      - name: run netdev tests
        run: sudo -E $(which cargo) test -p netdev

      - name: run wgshim tests
        run: sudo -E $(which cargo) test -p wgshim -- --test-threads 1

      - name: install clang tools
        run: sudo apt-get update && sudo apt-get install -y clang clang-format clang-tidy

      - name: run clang-format
        run: clang-format --dry-run -Werror wgshim/src/libwgshim/libwgshim.* netdev/src/libnetdev/libnetdev.*

      - name: run clang-tidy
        run: clang-tidy netdev/src/libnetdev/libnetdev.* wgshim/src/libwgshim/libwgshim.*