name: tag

on:
  push:
    branches: [main]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: install semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/commit-analyzer @semantic-release/exec conventional-changelog-conventionalcommits

      - name: run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
