name: tests

on:
  pull_request:
    branches: [ main ]

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: generate cargo cache key
        id: cache-key
        run: echo "key=${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}" >> $GITHUB_OUTPUT

  conventional_commit_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check conventional commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.yml

  rust_format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: cargo fmt
        run: cargo fmt --all -- --check

  rust_tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install deps
        run: sudo apt-get update && sudo apt-get install -y iproute2 wireguard-tools

      - name: wghttp tests
        run: cargo test -p wghttp

      - name: netdev tests
        run: sudo -E $(which cargo) test -p netdev

      - name: wgshim tests
        run: sudo -E $(which cargo) test -p wgshim -- --test-threads 1

  clang_format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: run clang-format
        run: clang-format --dry-run -Werror wgshim/src/libwgshim/libwgshim.* netdev/src/libnetdev/libnetdev.*

  clang_tidy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install clang-tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy

      - name: run clang-tidy
        run: clang-tidy netdev/src/libnetdev/libnetdev.* wgshim/src/libwgshim/libwgshim.* -- -Iinclude
